// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://llpltjjcprminnkujpaz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxscGx0ampjcHJtaW5ua3VqcGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0NjMwNzYsImV4cCI6MjA0OTAzOTA3Nn0.eAV3SBGqvuHLJgQZsEzdm3xm6Wmu-gAh4ncZomvFp4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);